package com.excitel.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.io.Serializable;

import lombok.*;
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Builder
@DynamoDBTable(tableName = "connection-table")
public class BroadbandConnection implements Serializable {
//    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "ConnectionID")
    private String connectionId;

    @DynamoDBAttribute(attributeName = "CustomerName")
    private String name;

    @DynamoDBAttribute(attributeName = "Address")
    private String address;

    @DynamoDBAttribute(attributeName = "PINCode")
    private String pinCode;

    @DynamoDBAttribute(attributeName = "City")
    private String city;

    @DynamoDBAttribute(attributeName = "State")
    private String state;

    @DynamoDBAttribute(attributeName = "Country")
    private String country;

    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = "ConnectionStatus")
    private String status = "Active";

//    @NotNull(message = "Mobile number must not be null")
//    @NotEmpty(message = "Mobile number must not be empty")
    @DynamoDBRangeKey
    @DynamoDBAttribute(attributeName = "MobileNumber")
    private String mobileNumber;

}
